_target_: src.model.HiFiGAN

generator_config:
  mel_channels: 80
  hidden_channels: 128
  transpose_kernels: [16, 16, 4, 4]
  mrf_config:
    kernel_sizes: [3, 7, 11]
    dilations: [[[1, 3, 5], [1, 3, 5], [1, 3, 5]], 
                [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 
                [[1, 3, 5], [1, 3, 5], [1, 3, 5]]]
    

discriminator_config:
  msd_config: null
  mpd_config: null
