defaults:
  - model: hifi_gan
  - writer: wandb
  - metrics: example
  - datasets: lj_speech_dataset
  - dataloader: example
  - transforms: example
  - _self_
optimizer:
  generator:
    _target_: torch.optim.Adam
    lr: 3e-4
    betas: [0.8, 0.99]
  discriminator:
    _target_: torch.optim.Adam
    lr: 3e-4
    betas: [0.8, 0.99]
lr_scheduler:
  generator:
    _target_: torch.optim.lr_scheduler.StepLR
    gamma: 0.9
    step_size: ${trainer.epoch_len}
  discriminator:
    _target_: torch.optim.lr_scheduler.StepLR
    gamma: 0.9
    step_size: ${trainer.epoch_len}

loss_function:
  _target_: src.loss.HiFiGANLoss
  lambda_fm: 10.0
  lambda_mel: 45.0
trainer:
  log_step: 10
  n_epochs: 5
  epoch_len: 1000
  device_tensors: ["mel_spec", "true_wav"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: cuda # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
